### ISSUE TITLE
CTA to deploy on Azure

### ISSUE THREAD

**Issue by FloorD** [WebDev-Beginners/7-bank-project#4]
@sinedied do we want to add a reference / button to deploy to Azure at the end of this lesson?

**Comment by sinedied** [comment]
This could a nice idea, but it's not doable easily, as a server is required and it's currently a full Node.js server that would also needs to be deployed on its own.

The best solution I can think of would be to add a wrapper to make the server work with Azure Functions, and deploy everything as an Azure Static Web app. Still it would need a dedicated section for this (lesson 5?) as the config needs to be changed, a GitHub repo needs to be created with the server code included, so it's not really a 1 click deploy button.

**Comment by jlooper** [comment]
What about the terrarium or space game? Those could be ASWA-ready without a reconfiguration perhaps?

**Comment by sinedied** [comment]
Yes, for those two adding a deploy button should be quite straightforward

**Comment by jlooper** [comment]
I've added the button for terrarium and space, so closing
